name: Release to Homebrew
on:
  workflow_run:
    workflows: ["Release to PyPI"]
    types:
      - completed
  workflow_dispatch:
jobs:
  homebrew-core:
    runs-on: ubuntu-latest
    steps:
    - uses: mislav/bump-homebrew-formula-action@v2
      with:
        formula-name: dotdrop
      env:
        COMMITTER_TOKEN: ${{secrets.HOMEBREW_FORMULA_GH_TOKEN}}
