name: Release to Homebrew
on:
  workflow_run:
    workflows: ["Release to PyPI"]
    types:
      - completed
  workflow_dispatch:
jobs:
  homebrew-core:
    runs-on: ubuntu-latest
    steps:
    - uses: dawidd6/action-homebrew-bump-formula@v3
      with:
        token: ${{secrets.HOMEBREW_FORMULA_GH_TOKEN}}
        formula: dotdrop
